export const getPatientsKey = "GET_PATIENTS"
export const searchPatientKey = "SEARCH_PATIENT"
export const getKpPrevpatientsKey = "GET_KP_PREV_PATIENTS"
export const getHtsCodeKey = "GET_HTS_CODE"
export const getPrepCodeKey = "GET_PREP_CODE"
export const getKpPrevRecordByPatientIdKey = "GET_KP_PREV_RECORD_BY_PATIENT_ID"
export const getCombinedHtsPrepCodeKey = "GET_COMBINED_HTS_PREP"
export const getPatientByIdKey = "GET_PATIENT_BY_ID"
export const getPatientHivEnrolmentKey = "GET_PATIENT_HIV_ENROLMENT"
export const getStatesKey = "GET_STATES"
export const getProvincesKey = "GET_PROVINCES"
export const getCodesetsKey = "GET_CODESETS"
export const getTargetGroupKey = "TARGET_GROUP"
export const getTbStatusKey = "TB_STATUS"
export const getStiTreatmentKey = "STI_TREATMENT"
export const getMhpssKey = "MHPSS_PROVIDED"

