import { useFormik } from "formik";
import * as yup from "yup";
import { generateRandomString } from "../../utils";

export const useKpPrevFormValidationSchema = (onSubmit, initialValues) => {
  const randomString = generateRandomString(10);
  const kpPrevFormIntialValues = {
    htsClientCode: "",
    knownPositive: "",
    prevCode: `kp_kprev-${randomString}`,
    kpPatientState: "",
    patientState: "",
    patientProvince: "",
    patientTargetGroup: "",
    dateServiceOffered: "",
    patientArtNumber: "",
    offeredHts: "",
    acceptedHts: "",
    hivTestResult: "",
    referredForArt: "",
    offeredPrep: "",
    acceptedPrep: "",
    referredForPrep: "",
    condomDispensed: "",
    facilityReferredForFamilyPlanningServices: "",
    howManyCondomDispensed: "",
    lubricantsDispensed: "",
    howManyLubricantsDispensed: "",
    oralQuickDispensed: "",
    howManyOralQuickDispensed: "",
    newNeedleDispensed: "",
    howManyNewNeedleDispensed: "",
    oldNeedleRetrieved: "",
    howManyOldNeedleRetrieved: "",
    nalxoneProvided: "",
    howManyNalxoneProvided: "",
    iecMaterial: "",
    interPersonalCommunication: "",
    peerGroupCommunication: "",
    stiScreening: "",
    stiScreeningResult: "",
    stiTreatment: "",
    typeOfStiTreatment: "",
    stiFacilityReffered: "",
    stiSyndromicManagement: "",
    screenedForTb: "",
    providedWithTpt: "",
    tbTreatmentRefferal: "",
    tbFacilityReffered: "",
    screenedForViralHepatits: "",
    viralHepatitsScreenResult: "",
    offeredFamilyPlanningServices: "",
    referredForFamilyPlanningServices: "",
    providedWithinDrugRehab: "",
    offeredMhpss: "",
    typeOfMhpss: "",
    refferedFacilityDrugRehab: "",
    drugRehabFacilityReffered: "",
    onMedicalAssistedTherapy: "",
    receivedNalxoneForOverdoseTreatment: "",
    providedOrRefferedForEmpowerment: "",
    legalAidServiceType: "",
    typeLegalEmpowerment: "",
    legalProgramReferred: "",
    serviceProvider: "",
    typeEmpowermentprovided: "",
    facilityRefferedToRecievedNalxoneForOverdoseTreatment: "",
    empowermentProgramReferred: "",
    serviceProviderSignature: "",
    kpPatientTargetGroup: "",
  };

  const kpPrevFormInitialSchema = yup.object({
    dateServiceOffered: yup.date().required("This field is required"),
    htsClientCode: yup.mixed(),
    prevCode: yup.mixed(),
    knownPositive: yup.mixed(),
    patientState: yup.mixed(),
    facilityReferredForFamilyPlanningServices: yup.mixed(),
    kpPatientState: yup.mixed(),
    patientProvince: yup.mixed(),
    patientTargetGroup: yup.mixed(),
    kpPatientTargetGroup: yup.mixed().required("This field is required"),
    patientArtNumber: yup.mixed(),
    offeredHts: yup.mixed(),
    acceptedHts: yup.mixed(),
    hivTestResult: yup.mixed(),
    referredForArt: yup.mixed(),
    offeredPrep: yup.mixed(),
    acceptedPrep: yup.mixed(),
    referredForPrep: yup.mixed(),
    condomDispensed: yup.mixed(),
    howManyCondomDispensed: yup.mixed().test(
      'is-positive',
      'The number must be positive',
      value => value === undefined || value === null || (typeof Number(value) === 'number' && Number(value) > 0)
    ),
    lubricantsDispensed: yup.mixed(),
    howManyLubricantsDispensed: yup.mixed().test(
      'is-positive',
      'The number must be positive',
      value => value === undefined || value === null || (typeof Number(value) === 'number' && Number(value) > 0)
    ),
    oralQuickDispensed: yup.mixed(),
    howManyOralQuickDispensed: yup.mixed().test(
      'is-positive',
      'The number must be positive',
      value => value === undefined || value === null || (typeof Number(value) === 'number' && Number(value) > 0)
    ),
    newNeedleDispensed: yup.mixed(),
    howManyNewNeedleDispensed: yup.mixed().test(
      'is-positive',
      'The number must be positive',
      value => value === undefined || value === null || (typeof Number(value) === 'number' && Number(value) > 0)
    ),
    oldNeedleRetrieved: yup.mixed(),
    howManyOldNeedleRetrieved: yup.mixed().test(
      'is-positive',
      'The number must be positive',
      value => value === undefined || value === null || (typeof Number(value) === 'number' && Number(value) > 0)
    ),
    nalxoneProvided: yup.mixed(),
    howManyNalxoneProvided: yup.mixed().test(
      'is-positive',
      'The number must be positive',
      value => value === undefined || value === null || (typeof Number(value) === 'number' && Number(value) > 0)
    ),
    iecMaterial: yup.mixed(),
    interPersonalCommunication: yup.mixed(),
    peerGroupCommunication: yup.mixed(),
    stiScreening: yup.mixed(),
    stiScreeningResult: yup.mixed(),
    stiTreatment: yup.mixed(),
    typeOfStiTreatment: yup.mixed(),
    stiFacilityReffered: yup.mixed(),
    stiSyndromicManagement: yup.mixed(),
    screenedForTb: yup.mixed(),
    providedWithTpt: yup.mixed(),
    tbTreatmentRefferal: yup.mixed(),
    tbFacilityReffered: yup.mixed(),
    screenedForViralHepatits: yup.mixed(),
    vaccinationForViralHepatits: yup.mixed(),
    viralHepatitsScreenResult: yup.mixed(),
    offeredFamilyPlanningServices: yup.mixed(),
    referredForFamilyPlanningServices: yup.mixed(),
    providedWithinDrugRehab: yup.mixed(),
    offeredMhpss: yup.mixed(),
    typeOfMhpss: yup.mixed(),
    refferedFacilityDrugRehab: yup.mixed(),
    drugRehabFacilityReffered: yup.mixed(),
    onMedicalAssistedTherapy: yup.mixed(),
    receivedNalxoneForOverdoseTreatment: yup.mixed(),
    providedOrRefferedForEmpowerment: yup.mixed(),
    legalAidServiceType: yup.mixed(),
    typeLegalEmpowerment: yup.mixed(),
    legalProgramReferred: yup.mixed(),
    serviceProvider: yup.mixed(),
    typeEmpowermentprovided: yup.mixed(),
    empowermentProgramReferred: yup.mixed(),
    serviceProviderSignature: yup.mixed(),
    facilityRefferedToRecievedNalxoneForOverdoseTreatment: yup.mixed(),
  });

  const formik = useFormik({
    initialValues: initialValues
      ? { ...kpPrevFormIntialValues, ...initialValues }
      : kpPrevFormIntialValues,
    onSubmit,
    validationSchema: kpPrevFormInitialSchema,
  });
  return { formik };
};
